### ISSUE TITLE
[Website] Change the font of the website to match Figma

### ISSUE THREAD

**Issue by sloh4137** [TACL-LYF/lyf-website#11]
# Goal
Currently, the font of our website is the default Material UI font, and we want to use our brand font instead.

May need to ask for the font name from Bianca and Rae and figure out where to download it from if it's not a google hosted font

# How-To
1. Create a separate branch for this issue ([`git checkout -b [name of branch]`](https://git-scm.com/docs/git-checkout))
2. Go src/components/App
3. Follow Material UI's [typography theme customization](https://mui.com/material-ui/customization/typography/) tutorial for how to change the font
4. Create pull request and add Stephan as a reviewer to have it merged!

**Comment by aawangl** [comment]
I should be able to get to this this week~

**Comment by sloh4137** [comment]
Asked Bianca for a new font! We're using Nunito now which is supported as a Google font
