### ISSUE TITLE
[All Pages] Add helmet tab text

### ISSUE THREAD

**Issue by sloh4137** [TACL-LYF/lyf-website#24]
# Context
Every tab has helper text that describes what the tab is at a glance. We're missing that right now woops

*Estimated Size*: XS

# To-Do
Similar to lyf-registration/website, we need to add this text to every page by adding a HeadFC component 

You can create a util function [like I did in lyf-registration/website](https://github.com/TACL-LYF/lyf-registration/blob/main/website/src/utils/getPageTitle.tsx) or you can just add HeadFC to every page

You can see all the pages under [/src/pages](https://github.com/TACL-LYF/lyf-website/tree/main/src/pages)

**Comment by aawangl** [comment]
EDIT: Oh nvm, you're just using the reg website as an example! 

Hmm did you create this issue under the wrong repo? This seems like a registration website task?

**Comment by sloh4137** [comment]
Yeah just used that site as an example!
